on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Update readme according to Go doc
          uses: ./
          with:
            recursive: 'true'
            badge-travisci: 'true'
            badge-codecov: 'true'
            badge-godoc: 'true'
        - name: Save readme diff
          uses: actions/upload-artifact@v1
          with:
            name: Readme diff
            path: readme_diff.txt
